services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - microservices-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - kafka
    networks:
      - microservices-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/ipanaque94/config-repo
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: true
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
    restart: unless-stopped

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    depends_on:
      - config-server
    restart: unless-stopped

  transaction-service:
    container_name: transaction-service
    build:
      context: ./MS-transaction
    ports:
      - "8181:8181"  # ← AGREGADO: Puerto faltante
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Resto se obtiene del config-repo, solo lo mínimo aquí
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      kafka:
        condition: service_started
      schema-registry:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - microservices-network
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ms-api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      APP_JWT_SECRET: miclavesecretamuyseguraymuylarga12345678901234567890
      APP_JWT_EXPIRATION_MS: 3600000
    
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      transaction-service:
        condition: service_started  # ← AGREGADO: Esperar a transaction-service
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
